##### **MNIST Dataset: Digit Classifier from Scratch**

In [1]:
import numpy as np
import math

class Value:
    def __init__(self, mydata, _children=(), op='', label=''):
        self.data = mydata
        self._prev = set(_children)
        self._backward = lambda: None
        self._op = op
        self.grad = 0
        self.label = label
    
    def __repr__(self):
        return f'Value(data={self.data})'

    def __add__(self,other):
        other = other if isinstance(other,Value) else Value(other)
        ans = Value(self.data + other.data,(self,other), op='+')
        def _backward():
            self.grad += ans.grad
            other.grad += ans.grad
        ans._backward = _backward
        return ans
    
    def __radd__(self,other):
        return self + other

    def __mul__(self,other):
        # self = self if isinstance(self,Value) else Value(self) # its nonsense to do this to handle reverse part -> 2 * a (beacuse it is 2.__mul__(a); And you have custom __mul__ for a and not for 2)
        other = other if isinstance(other,Value) else Value(other)
        ans = Value(self.data * other.data,(self,other) , op='*')
        def _backward():
            self.grad += ans.grad*other.data
            other.grad += ans.grad*self.data
        ans._backward = _backward
        return ans
    
    def __rmul__(self, other):  # for reverse part -> other * self (Python checks for it if simple __mul__ doesn't hold)
        return self * other
    
    def __truediv__(self,other):
        return self * other**-1
    
    def __pow__(self, other):
        assert isinstance(other, (int, float))
        ans = Value(self.data**other, (self,), op=f'pow {other}')
        def _backward():
            self.grad += other* self.data**(other-1) * ans.grad
        ans._backward = _backward

        return ans
    
    
    def exp(self):
        x = self.data
        ans = Value(np.exp(x),(self,), op='exp')
        def _backward():
            self.grad += ans.grad * ans.data 

        ans._backward = _backward

        return ans

    def tanh(self):
        x = self.data
        t = (np.exp(2*x) - 1)/(np.exp(2*x) + 1)
        ans = Value(t,(self,),'tanh')
        def _backward():
            self.grad += ans.grad*(1-t**2)
            # self._backward()
        ans._backward = _backward

        return ans
    
    def relu(self):
        r = self.data
        if (r<0):
            r = 0
        ans = Value(r, (self,), op='ReLU')

        def _backward():
            self.grad += ans.grad * (self.data>0)

        ans._backward = _backward

        return ans
    
    # def softmax(self):
        
    # def log(self):
    #     assert self.data > 0, "Logarithm is undefined for non-positive values"
    #     ans = Value(np.log(self.data), (self,), op="log")

    #     def _backward():
    #         self.grad += (ans.grad / self.data)  # d/dx (ln x) = 1/x

    #     ans._backward = _backward
    #     return ans

    def log(self, epsilon=1e-7):
        ans = Value(math.log(self.data + epsilon), (self,), 'log')

        def _backward():
            self.grad += (1/(self.data + epsilon)) * ans.grad
            
        ans._backward = _backward

        return ans

    
    def __neg__(self): # -self
        return self * -1
    
    def __sub__(self, other):
        return self + (-other)
    
    def __rsub__(self, other): # other - self (eg: 1 - a)
        # print("I came here")
        return (-self) + other
        # return other - self
    
    # def __lt__(self, other):
    #     other = other if isinstance(other, Value) else Value(other)
    #     return self.data < other.data

    def __le__(self, other):
        # other = other if isinstance(other, Value) else Value(other)
        return self.data <= other.data

    # def __eq__(self, other):
    #     other = other if isinstance(other, Value) else Value(other)
    #     return self.data == other.data

    # def __ne__(self, other):
    #     other = other if isinstance(other, Value) else Value(other)
    #     return self.data != other.data

    def __ge__(self, other):
        # other = other if isinstance(other, Value) else Value(other)
        return self.data >= other.data

    def __gt__(self, other):
        # other = other if isinstance(other, Value) else Value(other)
        return self.data > other.data
    
    def backward(self):
        topo = []
        visited = set()
        def build_topo(i):
            if i not in visited:
                # visited.insert(i)
                visited.add(i)
                for prev in i._prev:
                    build_topo(prev)
                topo.append(i)

        build_topo(self)

        self.grad = 1
        for i in reversed(topo):
            i._backward()

In [2]:
a = Value(4)
b = Value(5)
a+b

Value(data=9)

In [3]:
# from micrograd_modified.engine import Value
import numpy as np
from sklearn.metrics import accuracy_score

class Neuron:

    def __init__(self, nin:int, act_fn:str = "relu"):
        # limit = np.sqrt(6 / nin)
        # self.w = [Value(np.random.uniform(-limit, limit)) for _ in range(nin)]
        # self.w = [Value(np.random.normal(-1,1)) for i in range(nin)]
        self.w = [Value(np.random.uniform(-1,1)) for i in range(nin)]
        self.b = Value(0)
        self.act_fn = act_fn
    
    def __call__(self,x):
        # out = sum((wi*xi for wi, xi in zip(self.w, x))) + self.b
        out = sum((wi*xi for wi, xi in zip(self.w, x)), self.b) # efficient than above line as sum takes an option 2nd argument, that is by default  = 0
        # activ = out

        if (self.act_fn=="relu"):
            activ = out.relu()
            return activ
        
        elif self.act_fn=="tanh":
            activ = out.tanh()
            return activ
        
        else:
            activ = out
            return activ
    
    def parameters(self):
      return self.w + [self.b]
    

class Layer:

    def __init__(self, nin:int, nout:int, activation_fn:str):  # nout for no. of neurons = output.size
        self.neurons = [Neuron(nin, activation_fn) for i in range(nout)]
        self.activ_fn = activation_fn

    def __call__(self, x):
        if (self.activ_fn=="softmax"):
            # print("I was here")
            out = [n(x) for n in self.neurons]
            # max_value = max(out)

            max_value = Value(max([v.data for v in out]))

            norm_out = [(it - max_value).exp() for it in out]
            denom = sum(norm_out)
            # for val in range(1,len(norm_out)):
            #     denom += norm_out[val]
            ans =  [(it/denom) for it in norm_out]
            return ans[0] if len(ans)==1 else ans
        
        else:
            ans2 = [n(x) for n in self.neurons]
            return ans2[0] if len(ans2)==1 else ans2

        # return out[0] if (len(out)==1) else out
    
    def parameters(self):
        return [p for n in self.neurons for p in n.parameters()]
    

class MLP:
    
    def __init__(self, nin, nouts:list, activations:list):
        netsize = [nin] + nouts
        self.Layers = [Layer(netsize[i],netsize[i+1],activations[i]) for i in range(len(nouts))]
        self.nin = nin
        # self.ytrue = y


    def __call__(self, x):
        out = x
        for Li in self.Layers:
            out = Li(out)
        return out
    
    def MSE(self,y, y_preed):
        Loss = sum([(yp-yt)**2 for yp,yt in zip(y_pred, y)])
        return Loss

    def cross_entropy_loss(self,y, y_pred):
        n = len(y)
        cumloss = 0
        y_for_accuracy = []
        for ind, yind in enumerate(y):
            cumloss -= y_pred[ind][yind].log()
            y_for_accuracy.append(np.argmax(y_pred[ind]).item())
        # loss = -sum([y_pred[ind][yind].log() for ind, yind in enumerate(y)]) /n
        loss = cumloss / n
        acc = accuracy_score(y,y_for_accuracy)
        
        return loss, acc
        
    def parameters(self):
        return [p for layer in self.Layers for p in layer.parameters()]

    def train(self, X, y, epochs, batch_size=30):
        num_samples = len(X)
        num_batches = num_samples // batch_size  # Number of batches per epoch

        for epoch in range(epochs):
            indices = np.arange(num_samples)
            np.random.shuffle(indices)

            for i in range(num_batches):
                # indices
                batch_indices = indices[i * batch_size:(i + 1) * batch_size]
                X_batch = X[batch_indices]
                y_batch = y[batch_indices]

                # forward-pass
                y_pred_batch = np.array([self(xi) for xi in X_batch])
                Loss, acc = self.cross_entropy_loss(y_batch, y_pred_batch)

                # zero-grad
                for param in self.parameters():
                    param.grad = 0

                # back-pass
                Loss.backward()

                # upadte
                learning_rate = 1.0 - 0.9 * (epoch * num_batches + i) / (epochs * num_batches)
                for param in self.parameters():
                    param.data -= learning_rate * param.grad

                print(f"Iter : {i} | Loss : {Loss.data} | Accuracy : {acc*100}")

            # Print loss/accuracy for monitoring
            print("-"*15)
            print(f"Epoch {epoch + 1}/{epochs}, Loss: {Loss}, Accuracy: {acc}")
            print("-"*15)

##### **Now let's train a MLP**

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

## **Training on MNIST dataset**

In [5]:
df = pd.read_csv("/kaggle/input/mnist-train/mnist_train.csv")
df.head(5)

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
y = df['label'].to_numpy()
# X = df.iloc[:,1:].to_numpy()
X = df.iloc[:, 1:].to_numpy().astype(np.float32) / 255.0

In [7]:
X = X[:5000]
y = y[:5000]

In [8]:
n = MLP(784, [10,10], ["relu", "softmax"])

In [9]:
n(X[0])

[Value(data=0.0019704234008873405),
 Value(data=0.10686071431741975),
 Value(data=1.0824307885164094e-07),
 Value(data=0.23137841682271376),
 Value(data=0.00023668014693804392),
 Value(data=0.5903701144667337),
 Value(data=0.006580175963631918),
 Value(data=0.052062546589403215),
 Value(data=1.4853441599957638e-07),
 Value(data=0.010540671514777505)]

In [10]:
n.train(X,y,10, 32)

Iter : 0 | Loss : 5.392449243350472 | Accuracy : 21.875
Iter : 1 | Loss : 5.256089438003693 | Accuracy : 6.25
Iter : 2 | Loss : 2.3370217827652353 | Accuracy : 21.875
Iter : 3 | Loss : 2.4851610647082887 | Accuracy : 9.375
Iter : 4 | Loss : 2.1231112613100374 | Accuracy : 21.875
Iter : 5 | Loss : 2.3168053564648616 | Accuracy : 15.625
Iter : 6 | Loss : 2.230587503923312 | Accuracy : 18.75
Iter : 7 | Loss : 2.007102078634883 | Accuracy : 28.125
Iter : 8 | Loss : 2.034283298329211 | Accuracy : 25.0
Iter : 9 | Loss : 1.9853225500151204 | Accuracy : 37.5
Iter : 10 | Loss : 1.6700463333652689 | Accuracy : 37.5
Iter : 11 | Loss : 2.326989152976418 | Accuracy : 28.125
Iter : 12 | Loss : 1.9770513377774273 | Accuracy : 34.375
Iter : 13 | Loss : 2.5268485187124576 | Accuracy : 21.875
Iter : 14 | Loss : 2.172368683138432 | Accuracy : 21.875
Iter : 15 | Loss : 2.111468625935101 | Accuracy : 28.125
Iter : 16 | Loss : 2.319246888304545 | Accuracy : 15.625
Iter : 17 | Loss : 2.112988634251283 | Accuracy : 21.875
Iter : 18 | Loss : 2.052505055760182 | Accuracy : 31.25
Iter : 19 | Loss : 1.927670113891679 | Accuracy : 25.0
Iter : 20 | Loss : 2.2242752004791995 | Accuracy : 21.875
Iter : 21 | Loss : 1.698987967245873 | Accuracy : 37.5
Iter : 22 | Loss : 2.0282284143952913 | Accuracy : 28.125
Iter : 23 | Loss : 1.8973392038773387 | Accuracy : 21.875
Iter : 24 | Loss : 1.943340698302464 | Accuracy : 34.375
Iter : 25 | Loss : 1.8889323401553935 | Accuracy : 18.75
Iter : 26 | Loss : 1.48191419322576 | Accuracy : 50.0
Iter : 27 | Loss : 1.8252788797567472 | Accuracy : 37.5
Iter : 28 | Loss : 1.4405520490163908 | Accuracy : 43.75
Iter : 29 | Loss : 2.205399356836923 | Accuracy : 37.5
Iter : 30 | Loss : 1.7301145549142618 | Accuracy : 34.375
Iter : 31 | Loss : 1.6570513533085642 | Accuracy : 40.625
Iter : 32 | Loss : 2.261279273819198 | Accuracy : 21.875
Iter : 33 | Loss : 1.6124408324294313 | Accuracy : 46.875
Iter : 34 | Loss : 1.586140718918772 | Accuracy : 34.375
Iter : 35 | Loss : 1.9958618180452068 | Accuracy : 21.875
Iter : 36 | Loss : 2.054060238190553 | Accuracy : 18.75
Iter : 37 | Loss : 1.8256589087231694 | Accuracy : 50.0
Iter : 38 | Loss : 1.601331352518636 | Accuracy : 37.5
Iter : 39 | Loss : 1.4982695161997264 | Accuracy : 40.625
Iter : 40 | Loss : 1.859368290338521 | Accuracy : 28.125
Iter : 41 | Loss : 2.180515858234026 | Accuracy : 28.125
Iter : 42 | Loss : 1.8588226324952448 | Accuracy : 53.125
Iter : 43 | Loss : 1.6235295293687806 | Accuracy : 40.625
Iter : 44 | Loss : 1.7440968557353473 | Accuracy : 37.5
Iter : 45 | Loss : 2.020467773065098 | Accuracy : 12.5
Iter : 46 | Loss : 1.6863199658517238 | Accuracy : 31.25
Iter : 47 | Loss : 1.380853313949571 | Accuracy : 50.0
Iter : 48 | Loss : 1.6988360658280626 | Accuracy : 31.25
Iter : 49 | Loss : 2.048531942213932 | Accuracy : 25.0
Iter : 50 | Loss : 1.4846332519824958 | Accuracy : 43.75
Iter : 51 | Loss : 1.9348650353639907 | Accuracy : 25.0
Iter : 52 | Loss : 1.6723123066358245 | Accuracy : 46.875
Iter : 53 | Loss : 1.2691502307794378 | Accuracy : 53.125
Iter : 54 | Loss : 1.3054811029037678 | Accuracy : 53.125
Iter : 55 | Loss : 1.5282918413045294 | Accuracy : 40.625
Iter : 56 | Loss : 1.5325016337346289 | Accuracy : 46.875
Iter : 57 | Loss : 2.1113604793964247 | Accuracy : 46.875
Iter : 58 | Loss : 1.7434580856367565 | Accuracy : 34.375
Iter : 59 | Loss : 1.6479804208451208 | Accuracy : 40.625
Iter : 60 | Loss : 1.6358043373110862 | Accuracy : 28.125
Iter : 61 | Loss : 1.5464514705824952 | Accuracy : 34.375
Iter : 62 | Loss : 1.5895452147906408 | Accuracy : 34.375
Iter : 63 | Loss : 1.7896524587174825 | Accuracy : 28.125
Iter : 64 | Loss : 1.7722245171764006 | Accuracy : 31.25
Iter : 65 | Loss : 1.382455432131475 | Accuracy : 50.0
Iter : 66 | Loss : 1.3560453627155324 | Accuracy : 50.0
Iter : 67 | Loss : 1.7634951346614625 | Accuracy : 43.75
Iter : 68 | Loss : 1.9542843728132417 | Accuracy : 21.875
Iter : 69 | Loss : 1.4548637687812747 | Accuracy : 43.75
Iter : 70 | Loss : 1.8342097008879115 | Accuracy : 31.25
Iter : 71 | Loss : 1.677063011357154 | Accuracy : 28.125
Iter : 72 | Loss : 1.4950463997597996 | Accuracy : 43.75
Iter : 73 | Loss : 1.4686596815731652 | Accuracy : 46.875
Iter : 74 | Loss : 1.8484247011345196 | Accuracy : 34.375
Iter : 75 | Loss : 1.6023374500219554 | Accuracy : 40.625
Iter : 76 | Loss : 1.3490305760541261 | Accuracy : 46.875
Iter : 77 | Loss : 1.2411597270332526 | Accuracy : 53.125
Iter : 78 | Loss : 1.7260658047510444 | Accuracy : 50.0
Iter : 79 | Loss : 1.1020863887621106 | Accuracy : 59.375
Iter : 80 | Loss : 2.0511773699136375 | Accuracy : 37.5
Iter : 81 | Loss : 1.4475507085095858 | Accuracy : 46.875
Iter : 82 | Loss : 1.3186683042497016 | Accuracy : 53.125
Iter : 83 | Loss : 1.7031945868393519 | Accuracy : 46.875
Iter : 84 | Loss : 1.8511045661101981 | Accuracy : 34.375
Iter : 85 | Loss : 1.6940847108493968 | Accuracy : 40.625
Iter : 86 | Loss : 1.4853943243330052 | Accuracy : 40.625
Iter : 87 | Loss : 1.402740336789677 | Accuracy : 40.625
Iter : 88 | Loss : 1.8010703067434088 | Accuracy : 31.25
Iter : 89 | Loss : 1.469536898735368 | Accuracy : 43.75
Iter : 90 | Loss : 1.6446621441423153 | Accuracy : 46.875
Iter : 91 | Loss : 1.6915194068882484 | Accuracy : 50.0
Iter : 92 | Loss : 1.732008403061885 | Accuracy : 37.5
Iter : 93 | Loss : 1.40137522733231 | Accuracy : 43.75
Iter : 94 | Loss : 1.2939204202658274 | Accuracy : 53.125
Iter : 95 | Loss : 1.3896656038354798 | Accuracy : 46.875
Iter : 96 | Loss : 1.3610950690890797 | Accuracy : 43.75
Iter : 97 | Loss : 1.9443839966797052 | Accuracy : 53.125
Iter : 98 | Loss : 1.2792005347331874 | Accuracy : 50.0
Iter : 99 | Loss : 1.0469833871072391 | Accuracy : 62.5
Iter : 100 | Loss : 1.4676824274668099 | Accuracy : 50.0
Iter : 101 | Loss : 1.0548720784431822 | Accuracy : 62.5
Iter : 102 | Loss : 1.3631414533791013 | Accuracy : 50.0
Iter : 103 | Loss : 1.0893771632727172 | Accuracy : 56.25
Iter : 104 | Loss : 1.714721818681901 | Accuracy : 31.25
Iter : 105 | Loss : 0.9867204453199886 | Accuracy : 56.25
Iter : 106 | Loss : 1.2544881351647088 | Accuracy : 56.25
Iter : 107 | Loss : 1.4330797967609803 | Accuracy : 53.125
Iter : 108 | Loss : 1.3490095116240899 | Accuracy : 46.875
Iter : 109 | Loss : 1.1030241609541647 | Accuracy : 59.375
Iter : 110 | Loss : 0.9712673262116764 | Accuracy : 75.0
Iter : 111 | Loss : 1.2641400461476455 | Accuracy : 50.0
Iter : 112 | Loss : 1.4388391197093395 | Accuracy : 50.0
Iter : 113 | Loss : 1.1384279262990795 | Accuracy : 46.875
Iter : 114 | Loss : 1.2978540677520876 | Accuracy : 56.25
Iter : 115 | Loss : 1.003090609251882 | Accuracy : 56.25
Iter : 116 | Loss : 1.3205935259410189 | Accuracy : 50.0
Iter : 117 | Loss : 1.7620111025890688 | Accuracy : 46.875
Iter : 118 | Loss : 1.5852238585550458 | Accuracy : 40.625
Iter : 119 | Loss : 1.8182346793170332 | Accuracy : 40.625
Iter : 120 | Loss : 1.4128303968771743 | Accuracy : 43.75
Iter : 121 | Loss : 1.5455157878233918 | Accuracy : 53.125
Iter : 122 | Loss : 1.5733023027210944 | Accuracy : 46.875
Iter : 123 | Loss : 1.62455536750683 | Accuracy : 40.625
Iter : 124 | Loss : 1.123804241456302 | Accuracy : 56.25
Iter : 125 | Loss : 1.4294965929619132 | Accuracy : 50.0
Iter : 126 | Loss : 1.2170836438546342 | Accuracy : 43.75
Iter : 127 | Loss : 1.000142987343773 | Accuracy : 62.5
Iter : 128 | Loss : 1.3341820244751923 | Accuracy : 50.0
Iter : 129 | Loss : 1.205235445093752 | Accuracy : 50.0
Iter : 130 | Loss : 0.9193845651854197 | Accuracy : 68.75
Iter : 131 | Loss : 1.3277167721331993 | Accuracy : 53.125
Iter : 132 | Loss : 1.3280981472825215 | Accuracy : 53.125
Iter : 133 | Loss : 1.3676839130330543 | Accuracy : 46.875
Iter : 134 | Loss : 1.538550023795644 | Accuracy : 46.875
Iter : 135 | Loss : 1.7599458153402152 | Accuracy : 34.375
Iter : 136 | Loss : 1.6015638060368673 | Accuracy : 50.0
Iter : 137 | Loss : 1.5727799244593514 | Accuracy : 40.625
Iter : 138 | Loss : 1.4671041590821274 | Accuracy : 50.0
Iter : 139 | Loss : 1.4681115789723322 | Accuracy : 50.0
Iter : 140 | Loss : 1.5546268131155883 | Accuracy : 31.25
Iter : 141 | Loss : 2.0689887448925672 | Accuracy : 31.25
Iter : 142 | Loss : 1.8560066980148486 | Accuracy : 53.125
Iter : 143 | Loss : 0.9290298049417721 | Accuracy : 68.75
Iter : 144 | Loss : 1.3179307206797906 | Accuracy : 46.875
Iter : 145 | Loss : 1.56793059433483 | Accuracy : 62.5
Iter : 146 | Loss : 1.3314833349269255 | Accuracy : 53.125
Iter : 147 | Loss : 1.267694050401404 | Accuracy : 46.875
Iter : 148 | Loss : 0.9537999601736544 | Accuracy : 68.75
Iter : 149 | Loss : 1.6329870526646344 | Accuracy : 43.75
Iter : 150 | Loss : 1.2247237358218377 | Accuracy : 59.375
Iter : 151 | Loss : 1.3540992790917379 | Accuracy : 50.0
Iter : 152 | Loss : 1.3403162950155665 | Accuracy : 56.25
Iter : 153 | Loss : 1.1214831280335629 | Accuracy : 62.5
Iter : 154 | Loss : 1.4781210304506551 | Accuracy : 59.375
Iter : 155 | Loss : 1.2619916488636993 | Accuracy : 50.0
---------------
Epoch 1/10, Loss: Value(data=1.2619916488636993), Accuracy: 0.5
---------------
Iter : 0 | Loss : 0.8603374056463505 | Accuracy : 71.875
Iter : 1 | Loss : 1.3021112232206584 | Accuracy : 53.125
Iter : 2 | Loss : 1.3347179027896976 | Accuracy : 50.0
Iter : 3 | Loss : 1.0445596353861795 | Accuracy : 59.375
Iter : 4 | Loss : 1.4964771544046762 | Accuracy : 50.0
Iter : 5 | Loss : 1.5436074519330434 | Accuracy : 43.75
Iter : 6 | Loss : 1.215459172623384 | Accuracy : 53.125
Iter : 7 | Loss : 0.6142284524643336 | Accuracy : 78.125
Iter : 8 | Loss : 1.1550425499389916 | Accuracy : 65.625
Iter : 9 | Loss : 1.3660703093874311 | Accuracy : 37.5
Iter : 10 | Loss : 1.2629231447749614 | Accuracy : 62.5
Iter : 11 | Loss : 1.1809174353441017 | Accuracy : 56.25
Iter : 12 | Loss : 1.2862624651742522 | Accuracy : 59.375
Iter : 13 | Loss : 1.5404789067526423 | Accuracy : 46.875
Iter : 14 | Loss : 1.2027345990262233 | Accuracy : 56.25
Iter : 15 | Loss : 1.217816957648344 | Accuracy : 50.0
Iter : 16 | Loss : 1.5078376143939047 | Accuracy : 46.875
Iter : 17 | Loss : 1.12496830275561 | Accuracy : 53.125
Iter : 18 | Loss : 1.2899387492213725 | Accuracy : 53.125
Iter : 19 | Loss : 1.0978339650816353 | Accuracy : 53.125
Iter : 20 | Loss : 1.2033767487784832 | Accuracy : 59.375
Iter : 21 | Loss : 1.2547180186839209 | Accuracy : 50.0
Iter : 22 | Loss : 1.4591960000744377 | Accuracy : 50.0
Iter : 23 | Loss : 1.1326677276421129 | Accuracy : 53.125
Iter : 24 | Loss : 1.3030038116444091 | Accuracy : 53.125
Iter : 25 | Loss : 1.19029633172904 | Accuracy : 50.0
Iter : 26 | Loss : 1.052322941617717 | Accuracy : 65.625
Iter : 27 | Loss : 1.1005471864373062 | Accuracy : 75.0
Iter : 28 | Loss : 0.9628779972984529 | Accuracy : 56.25
Iter : 29 | Loss : 1.0155872699975756 | Accuracy : 62.5
Iter : 30 | Loss : 1.0691881222393123 | Accuracy : 56.25
Iter : 31 | Loss : 1.0792283534266163 | Accuracy : 65.625
Iter : 32 | Loss : 1.2832602001075577 | Accuracy : 53.125
Iter : 33 | Loss : 1.5299784448083957 | Accuracy : 43.75
Iter : 34 | Loss : 0.8284845602077318 | Accuracy : 65.625
Iter : 35 | Loss : 0.885530594879364 | Accuracy : 62.5
Iter : 36 | Loss : 0.862873275061527 | Accuracy : 65.625
Iter : 37 | Loss : 0.9435513178688536 | Accuracy : 62.5
Iter : 38 | Loss : 1.1503076270346488 | Accuracy : 53.125
Iter : 39 | Loss : 1.4316260906370366 | Accuracy : 50.0
Iter : 40 | Loss : 1.099097950159473 | Accuracy : 62.5
Iter : 41 | Loss : 1.173121918181451 | Accuracy : 53.125
Iter : 42 | Loss : 1.4464045574428346 | Accuracy : 62.5
Iter : 43 | Loss : 1.0604806949200118 | Accuracy : 53.125
Iter : 44 | Loss : 0.8179043254833547 | Accuracy : 65.625
Iter : 45 | Loss : 1.1358601083951756 | Accuracy : 50.0
Iter : 46 | Loss : 0.7237617714549642 | Accuracy : 71.875
Iter : 47 | Loss : 1.851161845918137 | Accuracy : 56.25
Iter : 48 | Loss : 1.379778312998081 | Accuracy : 46.875
Iter : 49 | Loss : 0.8729669370700697 | Accuracy : 75.0
Iter : 50 | Loss : 0.6459666985504219 | Accuracy : 87.5
Iter : 51 | Loss : 1.1847050686684473 | Accuracy : 68.75
Iter : 52 | Loss : 1.8476005125957748 | Accuracy : 53.125
Iter : 53 | Loss : 1.4933030262316367 | Accuracy : 62.5
Iter : 54 | Loss : 0.907858982069635 | Accuracy : 62.5
Iter : 55 | Loss : 1.120177503086849 | Accuracy : 56.25
Iter : 56 | Loss : 0.8963776067794911 | Accuracy : 71.875
Iter : 57 | Loss : 0.9308272427036346 | Accuracy : 68.75
Iter : 58 | Loss : 1.5546884835997292 | Accuracy : 50.0
Iter : 59 | Loss : 0.8196706007852728 | Accuracy : 71.875
Iter : 60 | Loss : 1.0633383600215265 | Accuracy : 56.25
Iter : 61 | Loss : 0.9802327994705957 | Accuracy : 65.625
Iter : 62 | Loss : 1.004809909351053 | Accuracy : 62.5
Iter : 63 | Loss : 1.0566319880567914 | Accuracy : 65.625
Iter : 64 | Loss : 1.187716313425722 | Accuracy : 56.25
Iter : 65 | Loss : 1.4199779102837533 | Accuracy : 50.0
Iter : 66 | Loss : 1.4029055193385833 | Accuracy : 56.25
Iter : 67 | Loss : 1.7899570754949485 | Accuracy : 50.0
Iter : 68 | Loss : 1.5577746731362936 | Accuracy : 50.0
Iter : 69 | Loss : 1.0831426746102688 | Accuracy : 75.0
Iter : 70 | Loss : 0.8497256768274036 | Accuracy : 68.75
Iter : 71 | Loss : 0.6451783434102648 | Accuracy : 81.25
Iter : 72 | Loss : 1.2188179310753697 | Accuracy : 65.625
Iter : 73 | Loss : 1.1267984430549698 | Accuracy : 56.25
Iter : 74 | Loss : 0.9002843616800278 | Accuracy : 71.875
Iter : 75 | Loss : 1.394267191489925 | Accuracy : 59.375
Iter : 76 | Loss : 0.9895005236834766 | Accuracy : 65.625
Iter : 77 | Loss : 1.79984123679954 | Accuracy : 62.5
Iter : 78 | Loss : 0.9682888472108525 | Accuracy : 59.375
Iter : 79 | Loss : 1.2868651513642042 | Accuracy : 56.25
Iter : 80 | Loss : 1.9365519698793852 | Accuracy : 53.125
Iter : 81 | Loss : 1.0132813192366426 | Accuracy : 62.5
Iter : 82 | Loss : 1.2099688114136427 | Accuracy : 53.125
Iter : 83 | Loss : 1.1408193555703807 | Accuracy : 65.625
Iter : 84 | Loss : 1.1567191186289858 | Accuracy : 53.125
Iter : 85 | Loss : 0.7787593013873257 | Accuracy : 81.25
Iter : 86 | Loss : 1.041798120036425 | Accuracy : 59.375
Iter : 87 | Loss : 1.2803794204195065 | Accuracy : 62.5
Iter : 88 | Loss : 1.0912854549423 | Accuracy : 56.25
Iter : 89 | Loss : 0.9182809787832787 | Accuracy : 71.875
Iter : 90 | Loss : 1.1155467528401561 | Accuracy : 65.625
Iter : 91 | Loss : 1.0633726793811928 | Accuracy : 53.125
Iter : 92 | Loss : 1.07084140219775 | Accuracy : 62.5
Iter : 93 | Loss : 0.9894045732759146 | Accuracy : 71.875
Iter : 94 | Loss : 1.0532092864166052 | Accuracy : 65.625
Iter : 95 | Loss : 1.0474207342614843 | Accuracy : 62.5
Iter : 96 | Loss : 1.1370848240698483 | Accuracy : 65.625
Iter : 97 | Loss : 1.0624422164163945 | Accuracy : 71.875
Iter : 98 | Loss : 1.2259902395296074 | Accuracy : 68.75
Iter : 99 | Loss : 0.5623374567871698 | Accuracy : 78.125
Iter : 100 | Loss : 3.168671907162611 | Accuracy : 40.625
Iter : 101 | Loss : 0.8990031619830327 | Accuracy : 71.875
Iter : 102 | Loss : 1.0205164940850764 | Accuracy : 65.625
Iter : 103 | Loss : 0.8570003176810858 | Accuracy : 81.25
Iter : 104 | Loss : 0.8445321042240098 | Accuracy : 68.75
Iter : 105 | Loss : 0.7678227883676499 | Accuracy : 65.625
Iter : 106 | Loss : 0.7426255419855718 | Accuracy : 65.625
Iter : 107 | Loss : 1.1490866238832698 | Accuracy : 59.375
Iter : 108 | Loss : 0.7360860709358472 | Accuracy : 68.75
Iter : 109 | Loss : 1.4063907645777458 | Accuracy : 62.5
Iter : 110 | Loss : 1.6722483067912899 | Accuracy : 46.875
Iter : 111 | Loss : 1.1602750673052153 | Accuracy : 56.25
Iter : 112 | Loss : 0.8968564056203621 | Accuracy : 59.375
Iter : 113 | Loss : 1.270652331351594 | Accuracy : 62.5
Iter : 114 | Loss : 0.7899970940168285 | Accuracy : 68.75
Iter : 115 | Loss : 0.9055909363189276 | Accuracy : 65.625
Iter : 116 | Loss : 1.3187560558533478 | Accuracy : 46.875
Iter : 117 | Loss : 1.2665048361687994 | Accuracy : 56.25
Iter : 118 | Loss : 0.9263274452063878 | Accuracy : 68.75
Iter : 119 | Loss : 0.5403802657671457 | Accuracy : 84.375
Iter : 120 | Loss : 1.0635908313041906 | Accuracy : 65.625
Iter : 121 | Loss : 1.0691280641913956 | Accuracy : 62.5
Iter : 122 | Loss : 1.2243823468012827 | Accuracy : 56.25
Iter : 123 | Loss : 1.0012845395046777 | Accuracy : 62.5
Iter : 124 | Loss : 0.8101166586974321 | Accuracy : 65.625
Iter : 125 | Loss : 0.7723738846799099 | Accuracy : 71.875
Iter : 126 | Loss : 1.178374565539514 | Accuracy : 68.75
Iter : 127 | Loss : 1.4369435617008255 | Accuracy : 53.125
Iter : 128 | Loss : 0.6745032714907133 | Accuracy : 75.0
Iter : 129 | Loss : 1.0405721955610947 | Accuracy : 65.625
Iter : 130 | Loss : 1.2564733229061682 | Accuracy : 59.375
Iter : 131 | Loss : 1.5735719013582576 | Accuracy : 50.0
Iter : 132 | Loss : 1.165943326838549 | Accuracy : 50.0
Iter : 133 | Loss : 1.0144395695791373 | Accuracy : 53.125
Iter : 134 | Loss : 1.078383301061444 | Accuracy : 65.625
Iter : 135 | Loss : 0.8447877860566234 | Accuracy : 62.5
Iter : 136 | Loss : 1.1412516006998537 | Accuracy : 53.125
Iter : 137 | Loss : 1.5424695410889526 | Accuracy : 59.375
Iter : 138 | Loss : 1.6651704717871572 | Accuracy : 50.0
Iter : 139 | Loss : 1.4154162234049745 | Accuracy : 59.375
Iter : 140 | Loss : 1.4087739371198087 | Accuracy : 46.875
Iter : 141 | Loss : 1.2572243385993886 | Accuracy : 56.25
Iter : 142 | Loss : 0.8198914599304864 | Accuracy : 68.75
Iter : 143 | Loss : 0.8683052360957412 | Accuracy : 78.125
Iter : 144 | Loss : 0.6988672435329546 | Accuracy : 75.0
Iter : 145 | Loss : 0.7277570883971217 | Accuracy : 78.125
Iter : 146 | Loss : 1.389414381545617 | Accuracy : 53.125
Iter : 147 | Loss : 0.8898518561089832 | Accuracy : 68.75
Iter : 148 | Loss : 1.2984310630731206 | Accuracy : 56.25
Iter : 149 | Loss : 0.9445142735158056 | Accuracy : 68.75
Iter : 150 | Loss : 1.1388182815426893 | Accuracy : 59.375
Iter : 151 | Loss : 0.9469080004669901 | Accuracy : 62.5
Iter : 152 | Loss : 1.2651256593478006 | Accuracy : 56.25
Iter : 153 | Loss : 0.8318923473909364 | Accuracy : 62.5
Iter : 154 | Loss : 0.9006629102673714 | Accuracy : 62.5
Iter : 155 | Loss : 0.9994236930935299 | Accuracy : 62.5
---------------
Epoch 2/10, Loss: Value(data=0.9994236930935299), Accuracy: 0.625
---------------
Iter : 0 | Loss : 0.6993975885938305 | Accuracy : 68.75
Iter : 1 | Loss : 1.2357809996770803 | Accuracy : 53.125
Iter : 2 | Loss : 0.8760723179681504 | Accuracy : 59.375
Iter : 3 | Loss : 0.9462348993027423 | Accuracy : 65.625
Iter : 4 | Loss : 0.7542272441082277 | Accuracy : 75.0
Iter : 5 | Loss : 1.1957023940106875 | Accuracy : 56.25
Iter : 6 | Loss : 0.9218833359304264 | Accuracy : 68.75
Iter : 7 | Loss : 0.7134833518554384 | Accuracy : 71.875
Iter : 8 | Loss : 1.3116922739395986 | Accuracy : 59.375
Iter : 9 | Loss : 1.037183221893022 | Accuracy : 68.75
Iter : 10 | Loss : 0.727399664492373 | Accuracy : 59.375
Iter : 11 | Loss : 1.4558069738626707 | Accuracy : 62.5
Iter : 12 | Loss : 0.9309094147613645 | Accuracy : 65.625
Iter : 13 | Loss : 0.5125897924518487 | Accuracy : 84.375
Iter : 14 | Loss : 0.8844710370714082 | Accuracy : 71.875
Iter : 15 | Loss : 0.5946867653222568 | Accuracy : 75.0
Iter : 16 | Loss : 1.0254353398443155 | Accuracy : 65.625
Iter : 17 | Loss : 0.7067598422868078 | Accuracy : 75.0
Iter : 18 | Loss : 1.1236914702895906 | Accuracy : 68.75
Iter : 19 | Loss : 0.9472994312504706 | Accuracy : 71.875
Iter : 20 | Loss : 0.7880325753973091 | Accuracy : 65.625
Iter : 21 | Loss : 0.8368618808343281 | Accuracy : 62.5
Iter : 22 | Loss : 0.6830588055345557 | Accuracy : 71.875
Iter : 23 | Loss : 1.2534167785205854 | Accuracy : 56.25
Iter : 24 | Loss : 1.0264179296335174 | Accuracy : 59.375
Iter : 25 | Loss : 1.0434482467657615 | Accuracy : 78.125
Iter : 26 | Loss : 1.3964091149024482 | Accuracy : 59.375
Iter : 27 | Loss : 1.0511841955711887 | Accuracy : 65.625
Iter : 28 | Loss : 0.6707039617562853 | Accuracy : 78.125
Iter : 29 | Loss : 0.6500087865184889 | Accuracy : 75.0
Iter : 30 | Loss : 0.7023689241562545 | Accuracy : 75.0
Iter : 31 | Loss : 0.7474029979682291 | Accuracy : 75.0
Iter : 32 | Loss : 1.2930820702340124 | Accuracy : 62.5
Iter : 33 | Loss : 0.7446215992817232 | Accuracy : 71.875

### **Testing time**

In [11]:
test_df = pd.read_csv("/kaggle/input/mnist-in-csv/mnist_test.csv")
test_df.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
y_test = df['label'].to_numpy()
# X = df.iloc[:,1:].to_numpy()
X_test = df.iloc[:, 1:].to_numpy().astype(np.float32) / 255.0

In [13]:
y_pred_new = []
for xi in X_test[:200]:
    y_pred_new.append(np.argmax(n(xi)).item())
y_pred_new = np.array(y_pred_new)

In [14]:
from sklearn.metrics import accuracy_score
print(f"Test Accuracy: {accuracy_score(y_test[:200],y_pred_new)*100}%")

Test Accuracy: 87.5%